# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup build environment
        run: sudo apt-get install fpc gcc nasm python3
        
      - name: CD
        run: cd /home/runner/work/obcomp/obcomp

      - name: Build the compiler
        run: make build
        
      - name: Run some tests
        run: make test

